const products = [
  {
    name: "Żelazko",
    price: 222.99,
    priceWithDelivery: 11.47,
    category: "Elektronika",
    peopleBuy: 27,
    state: "Nowy",
    imgSrc: "./images/zelazko.jpg",
  },
  {
    name: "Piłka Adidas Jabulani 2010",
    price: 99.29,
    priceWithDelivery: 8.99,
    category: "Sport i turystyka",
    peopleBuy: 4,
    state: "Nowy",
    imgSrc: "./images/jabulani.jpg",
  },
  {
    name: "Odkurzacz ZELMER",
    price: 599.0,
    priceWithDelivery: 18.99,
    category: "Elektronika",
    peopleBuy: 10,
    state: "Używany",
    imgSrc: "./images/zelmer.jpg",
  },
  {
    name: "W grze - Jerzy Brzęczek",
    price: 49.0,
    priceWithDelivery: 6.99,
    category: "Kultura i rozrywka",
    peopleBuy: 0,
    state: "Używany",
    imgSrc: "./images/jb.jpg",
  },
  {
    name: "Siłownik VOLVO FV-12",
    price: 2599.0,
    priceWithDelivery: 99.99,
    category: "Motoryzacja",
    peopleBuy: 1,
    state: "Nowy",
    imgSrc: "./images/sil.jpg",
  },
  {
    name: "Magnez kompleks",
    price: 15.99,
    priceWithDelivery: 6.99,
    category: "Zdrowie",
    peopleBuy: 40,
    state: "Nowy",
    imgSrc: "./images/magnez.jpg",
  },
  {
    name: "Tusz do rzęs",
    price: 19.95,
    priceWithDelivery: 5.99,
    category: "Uroda",
    peopleBuy: 5,
    state: "Nowy",
    imgSrc: "./images/tusz.jpg",
  },
  {
    name: "Meble ogrodowe",
    price: 1599.0,
    priceWithDelivery: 48.99,
    category: "Dom i ogród",
    peopleBuy: 11,
    state: "Używany",
    imgSrc: "./images/mo.jpg",
  },
  {
    name: "T-shirt damski",
    price: 39.29,
    priceWithDelivery: 6.99,
    category: "Moda",
    peopleBuy: 8,
    state: "Nowy",
    imgSrc: "./images/tsd.jpg",
  },
];
